### ISSUE TITLE
Resolve relative paths in --bodyFile based on the location relative to the yml file.

### ISSUE THREAD

**Issue by javiercn** [dotnet/crank#173]
I was playing with this today.

Had an action defined as follows:
```yml
    # Add product
  ApiCrudAddProduct:
    application:
      job: mvcServer
    load:
      job: bombardier
      variables:
        path: /Products
        verb: POST
        bodyFile: ./crudproductbody.json
```

and I kept getting errors because the file couldn't be found.

Upon investigation, it turned out that it was passing the value verbatim to bombardier, which didn't run in the same context.

Is it possible to resolve the file path relative to the location of the yml file?
