### ISSUE TITLE
Controller/Agent Authentication

### ISSUE THREAD

**Issue by giulianob** [dotnet/crank#376]
I need to protect any API I have in our network and it seems the agent does not provide any authentication currently.

Is there any mechanisms to make the agent API not publicly available? If not, I am imagining something like the following:
`crank-agent --api-key MYAPIKEY`
`crank --myjob.options.apiKey MYAPIKEY`

It could also be something fancier like JWT but having a proper OAuth/OIDC identity server may be too much for many users.

**Comment by sebastienros** [comment]
I decided to not support any form of authentication, and rely on network boundaries instead (like Redis or ElasticSearch for instance).
One mitigation is to put it in a private network, and use the Azure Relay option which is secured via an API key.

But I believe we could try to design a solution based on a middleware and a private key? Would probably be a simple solution. Would need to support multiple keys, and permissions (read/run jobs).

**Comment by giulianob** [comment]
I personally only need authN rather than authZ but I can see how that's useful for some folks. How do you see this being configured? 

Something like the following:
```yaml
profiles:
   somenode:
      apiKey:
        - key: MYSECRET1
          permissions: [ "read", "run" ]
        - key: MYSECRET2
          permissions: [ "read" ]
```
I wouldn't want to check this into source control so either I would put this in a `secrets.yaml` and include it in my main config or just specify it in the CLI. I am not sure how to specify a complex object array like that in the CLI though.
