### ISSUE TITLE
crank-pr cannot clone GitHub Enterprise-hosted repos

### ISSUE THREAD

**Issue by martincostello** [dotnet/crank#462]
I've recently come back around to investigating the use of crank again internally at my employer, where we use GitHub Enterprise Server, and found that `crank-pr` does not support cloning repositories from GHES within GitHub Actions as it does not send the appropriate authentication required to get permissions to the repositories.

I tried a few different approaches to cloning it with private builds, but the first few attempts failed.

## Using HTTPS

```sh
[/tmp/] git clone --recursive https://github.corp/owner/repo.git /tmp/repo -b main
[STDERR] Cloning into '/tmp/repo'...
[STDERR] fatal: could not read Username for 'https://github.corp/': No such device or address
```

## Using SSH

```sh
[/tmp/] git clone --recursive git@github.corp:owner/repo.git /tmp/repo -b main
[STDERR] Cloning into '/tmp/repo'...
[STDERR] Host key verification failed.
[STDERR] fatal: Could not read from remote repository.
[STDERR] 
[STDERR] Please make sure you have the correct access rights
[STDERR] and the repository exists.
```

## HTTPS with PAT as user name

```sh
[/tmp/] git clone --recursive https://***@github.corp/owner/repo.git /tmp/repo -b main
[STDERR] Cloning into '/tmp/repo'...
[STDERR] fatal: could not read Password for 'https://***@github.corp': No such device or address
```

I did eventually get this working with a private build by using a username of `x-access-token` like the [actions/checkout](https://github.com/actions/checkout/blob/2541b1294d2704b0964813337f33b291d3f8596b/src/git-auth-helper.ts#L58) action does, with the GitHub PAT as the password.

```sh
[/tmp/] git clone --recursive ***github.corp/owner/repo.git /tmp/repo -b main
[STDERR] Cloning into '/tmp/repo'...
[/tmp/repo] bash -c "dotnet build --configuration Release"
```

The code for this change can be found [here](https://github.com/dotnet/crank/commit/cc044815e2ff214a76f7e6568fcd71ea47f56c9c#diff-bb635becf09b6c767676d2474e10c0b99f19953288997cfd9e9111384fea81df).

With that resolved, that lead onto a second issue, though that can be worked around with configuration.

The `crank-agent` tool also has the same issue with cloning from GHES, but it can be overcome by specifying the job's repository explicitly when running `crank-pr` as an argument to pass through to the agent.

```sh
--arguments "--application.source.repository https://x-access-token:access-token@github.corp/owner/repo.git"
```

An example PowerShell script used to start the agent and invoke `crank-pr` with this approach is shown below along with the associated YAML files.

<details>

<summary>PowerShell script to run crank-pr</summary>

```powershell
param(
    [Parameter(Mandatory = $true)][string] $PullRequestId,
    [Parameter(Mandatory = $false)][string] $AccessToken,
    [Parameter(Mandatory = $false)][string] $Benchmark = "root",
    [Parameter(Mandatory = $false)][string] $CrankPath = "",
    [Parameter(Mandatory = $false)][string] $GitHubBaseUrl = "https://github.corp",
    [Parameter(Mandatory = $false)][string] $Repository = "https://github.corp/owner/repo"
)

$crankAgent = "crank-agent"
$crankPR = "crank-pr"

if (![string]::IsNullOrEmpty($CrankPath)) {
    $crankAgent = Join-Path $CrankPath $crankAgent
    $crankPR = Join-Path $CrankPath $crankPR
}

if ($IsWindows) {
    $agent = Start-Process -FilePath $crankAgent -WindowStyle Hidden -PassThru
} else {
    $agent = Start-Process -FilePath $crankAgent -PassThru
}

Start-Sleep -Seconds 2

$repoPath = Split-Path $MyInvocation.MyCommand.Definition
$components = "app"
$config = Join-Path $repoPath "benchmark.yml"
$profiles = "local"

$additionalArgs = @()

if (![string]::IsNullOrEmpty($AccessToken)) {
    $additionalArgs += "--access-token"
    $additionalArgs += $AccessToken
    $additionalArgs += "--publish-results"
    $additionalArgs += "true"

    # When running on GitHub Actions in GitHub Enterprise, crank will try and
    # clone using the HTTPS URL, which will fail as it lacks the appropriate
    # authentication details to do so. In this case, set the user information
    # in the repository URL using the access token so the clone will succeed.
    $uriBuilder = New-Object -TypeName System.UriBuilder -ArgumentList $Repository
    $uriBuilder.UserName = "x-access-token"
    $uriBuilder.Password = $AccessToken

    $authRepo = $uriBuilder.Uri.ToString()

    $additionalArgs += "--arguments"
    $additionalArgs += "`"--application.source.repository $authRepo`""
}

try {
    & $crankPR `
        --benchmarks $Benchmark `
        --components $components `
        --config $config `
        --github-base-url $GitHubBaseUrl `
        --profiles $profiles `
        --pull-request $PullRequestId `
        --repository $Repository `
        $additionalArgs
}
finally {
    Stop-Process -InputObject $agent -Force | Out-Null
}
```

</details>

<details>

<summary>benchmark.yml</summary>

```yml
components:
  app:
    script: |
      dotnet build --configuration Release
    arguments: ""

defaults: --config ./crank.yml

profiles:
  local:
    description: Local
    arguments: --profile local

benchmarks:
  root:
    description: Root
    arguments: --config ./crank.yml --scenario root
```

</details>

<details>

<summary>crank.yml</summary>

```yml
imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  server:
    source:
      repository: https://github.corp/owner/repo
      branchOrCommit: main
      project: src/App/App.csproj
    readyStateText: Application started.

scenarios:
  root:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs:
      application:
        endpoints:
          - http://localhost:5010
      load:
        endpoints:
          - http://localhost:5010
```

</details>

I can push up the PR to fix `crank-pr` if you think it's an acceptable change to always add the PAT, if there is one, to the clone URL. I didn't feel the fix was "neat" enough to be _the_ solution, particularly as it doesn't work neatly with `crank-agent`. Maybe there's a smarter/cleaner way to get this scenario working?

At least fixing the cloning issue with `crank-pr` in some way would remove the need for me to use local builds to get things working, as the other issue can just be worked around with configuration easily enough.
