### ISSUE TITLE
Can number of requests per second be customized?

### ISSUE THREAD

**Issue by ribubrar** [dotnet/crank#489]
Can requests be customized to edit RPS and ramp-up time for the benchmarked method?

**Comment by sebastienros** [comment]
Bombardier supports `rate` as a variable. You can use that to use a fixed RPS. It doesn't support variations, but this could be achieved with multiple load jobs (load1, load2, ...) with different rates, and each run would be saved independently. e.g.:

```
scenarios:
- test
  application:
    job: thebenchmark
  load1:
    job: bombardier
    variables:
      rate: 1000
  load2:
    job: bombardier
    variables:
      rate: 5000
  load3:
    job: bombardier
    variables:
      rate: 10000
```

Another option is to change one of the clients, for instance the HttpClient one, and improve it to support the ramping up. I think at one point I implemented it, will check if it's still supported (don't remember).

And remember that even if there is a single application job, all the samples are stored if you save the results in a json file (or sql) so you can see the progression of CPU usages or other server stats.
