### ISSUE TITLE
Exception: Sequence contains more than one element when trying to use Bombardier

### ISSUE THREAD

**Issue by ribubrar** [dotnet/crank#493]
I get an exception when trying to use below-mentioned benchmarks.yml
`Unhandled exception. System.InvalidOperationException: Sequence contains more than one element`

```
imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  benchmarks:
    source:
      localFolder: .
      project:  C:\Project\demo.csproj
    variables:
      filterArg: "*"
      jobArg: short
    arguments: --job {{jobArg}} --filter {{filterArg}} --memory
    options:
      benchmarkDotNet: true
    
scenarios:
  Md5VsSha256:
    application:
      job: benchmarks
    load:
      job: bombardier
      variables:
        serverPort: 5000
        rate: 5

profiles:
  local:
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
      load:
        endpoints: 
          - http://localhost:5010
```

Whereas when I use below `benchmarks.yml` it runs fine:

```
jobs:
  benchmarks:
    source:
      localFolder: .
      project: C:\Projects\demo.csproj
    variables:
      filterArg: "*"
      jobArg: short
    arguments: --job {{jobArg}} --filter {{filterArg}} --memory
    options:
      benchmarkDotNet: true
    
scenarios:
  Md5VsSha256:
    application:
      job: benchmarks

profiles:
  local:
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
```
