### ISSUE TITLE
[Proposal] Accept glob filter to calculate the set of files used for determining Published Size (KB)

### ISSUE THREAD

**Issue by mitchdenny** [dotnet/crank#513]
I think it would be good to be able to filter the set of files that are used to determine the `Published Size (KB)` metric. In my scenario I want to exclude certain files from the calculation which a user of the runtime wouldn't deploy to their production workloads. Some mechanism like this would be handy.

```yaml
scenarios:

  aotstage1:
    application:
      job: aspnetbenchmarks
      selfContained: true
      publishedSizeFilter:
        exclude:
          - !*.dbg
          - !*.json
      buildArguments: 
        - "/p:PublishAot=true"
        - "/p:StripSymbols=true"
        - "/p:DebugSymbols=false"
        - "/p:DebugType=None"
      variables:
        scenario: aotstage1
```
