### ISSUE TITLE
Support for multiple sources

### ISSUE THREAD

**Issue by caaavik-msft** [dotnet/crank#593]
Currently, each crank job can only have one source defined, however I would like to have a job that uses multiple sources. In my specific case, my sources would be the `dotnet/runtime` and `dotnet/performance` GitHub repositories as we want to run the benchmarks in the `dotnet/performance` repository against the latest code in `dotnet/runtime`.

I have two proposals for how this could possibly be supported in the yaml assuming that I had the above two sources and I wanted to use a csproj located at `/eng/runbenchmarks.csproj` in the `performance` repository. I have a local implementation of proposal 1 that I have been using for a proof of concept, but it has not been pushed yet anywhere that is visible. This local implementation can easily be adapted for proposal 2, and I am willing to implement this feature once we have decided on what the best approach is.

### Proposal 1 - Not Backwards Compatible
Replace `source` with `sources` which is a dictionary storing all the sources. The properties that describe what gets run such as `project` or the `docker` properties would get moved out so that the source information is not mixed in with how it gets run (and so it is consistent with the `executable` property we have today). This approach though would not be backwards compatible at all, but I think if we wanted to solve this without needing to maintain backwards compatibility, it is my favourite option. One critique about this though would be that for single-source jobs, the extra level of nesting is not bringing any benefits.
```yaml
sources:
  runtime:
    repository: https://github.com/dotnet/runtime
    branchOrCommit: main
    destination: /runtime # this could be omitted if we assume that `/{sourceName}` is the default  
  performance:
    repository: https://github.com/dotnet/performance
    branchOrCommit: main
    destination: /performance
project: /performance/eng/runbenchmarks.csproj
```

### Proposal 2 - Backwards Compatible
This is a backwards compatible option with the current approach. This option assumes that one source is going to be the primary source and will be placed under the `source` property like it is today. For extra sources, they would go under a dictionary-style property called `additionalSources` that will not allow you to specify a `project` or `docker` information.
```yaml
source:
  repository: https://github.com/dotnet/performance
  branchOrCommit: main
  project: /eng/runbenchmarks.csproj
additionalSources:
  runtime:
    repository: https://github.com/dotnet/runtime
    branchOrCommit: main
    destination: /runtime
```
